"""
enrich_abt.py
-------------
Fills the GIS placeholder columns in analytics_base_table.csv:

  1. Road network distances to key economic/infrastructure nodes (osmnx + networkx)
       dist_cebu_bp_m       — Cebu Business Park (primary CBD, empirical centroid)
       dist_itpark_m        — Cebu IT Park (BPO/tech hub, empirical centroid)
       dist_mandaue_cbd_m   — Mandaue commercial corridor (empirical centroid)
       dist_mactan_cbd_m    — Lapu-Lapu / Mactan commercial core (empirical centroid)
       dist_srp_m           — South Road Properties / SM Seaside (empirical centroid)
       dist_airport_m       — Mactan-Cebu International Airport
       dist_cbrt_nearest_m  — Nearest planned CBRT station

  CBD anchors are loaded from Data/processed/cbd_nodes.csv, generated by
  define_cbds.py using Google Maps Places API (Nearby Search, 1.5 km radius).
  Centroids are POI-weighted means — not arbitrary single-building pins.

  2. Amenity scores from OSM CSVs (counts within AMENITY_RADIUS_M)
       amenity_score_education
       amenity_score_health
       amenity_score_finance
       amenity_score_grocery
       amenity_score_transport
       amenity_score_security
       amenity_score_composite  (weighted index, see WEIGHTS below)

  3. Spatial lag
       spatial_lag_price   — Mean price of other properties within SPATIAL_LAG_RADIUS_M

Literature basis:
  - Road network distances: Boeing (2017); osmnx library
  - Haversine fallback: Sinnott (1984)
  - Proximity as value driver: Rosen (1974); Agosto (2020) — transport #1 driver in Cebu
  - Amenity scoring via OSM: Boeing (2017); Yao et al. (2018); Fonte et al. (2017)
  - Spatial lag: Tobler (1970); Anselin (1988)

Output: Data/processed/analytics_base_table.csv  (overwritten in-place)
"""

import math
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from network_utils import load_metro_cebu_graph, network_distances_from_sources

# ── Paths ──────────────────────────────────────────────────────────────────────
ABT_CSV      = "thesis_main/Data/processed/analytics_base_table.csv"
CBD_NODES_CSV = "thesis_main/Data/processed/cbd_nodes.csv"

AMENITY_CSVS = {
    "education":  "thesis_main/Data/amenities/education.csv",
    "health":     "thesis_main/Data/amenities/health.csv",
    "finance":    "thesis_main/Data/amenities/finance.csv",
    "grocery":    "thesis_main/Data/amenities/grocery.csv",
    "transport":  "thesis_main/Data/amenities/transport.csv",
    "security":   "thesis_main/Data/amenities/security.csv",
}

# ── Parameters ─────────────────────────────────────────────────────────────────
AMENITY_RADIUS_M    = 1_000   # 1 km walkable catchment (Boeing 2017; thesis §3.4.1)
SPATIAL_LAG_RADIUS_M = 1_000  # 1 km neighbour price mean (Tobler 1970)

# Amenity composite weights (Agosto 2020 ranking: transport > neighbourhood > environment)
# Finalised for Metro Cebu context; to be validated against SHAP during EDA.
WEIGHTS = {
    "transport":  0.25,
    "health":     0.25,
    "education":  0.20,
    "grocery":    0.15,
    "finance":    0.10,
    "security":   0.05,
}

# ── Reference node coordinates ────────────────────────────────────────────────
# CBD anchors loaded at runtime from cbd_nodes.csv (define_cbds.py output).
# Airport is fixed infrastructure — hardcoded.
AIRPORT = (10.307_19, 123.978_99)   # Mactan-Cebu International Airport

# Planned CBRT stations (Phase 1, south–north corridor)
# Source: DOTC/DOTr CBRT EIS alignment; coordinates from DOTr published maps.
CBRT_STATIONS = [
    (10.259_38, 123.843_11),  # SRP / SM Seaside area (southern terminus)
    (10.265_50, 123.851_83),  # Talisay boundary
    (10.275_40, 123.860_90),  # Bulacao
    (10.285_00, 123.868_00),  # Punta Princesa
    (10.293_90, 123.874_70),  # Labangon
    (10.302_60, 123.881_30),  # Kamagayan / Carbon market
    (10.313_70, 123.888_40),  # Colon / downtown Cebu
    (10.320_50, 123.893_60),  # Fuente Osmeña
    (10.327_30, 123.900_10),  # Capitol area
    (10.334_70, 123.905_20),  # Talamban road junction
    (10.343_00, 123.909_50),  # UC / Talamban
    (10.353_20, 123.913_00),  # Subangdaku / Mandaue boundary (northern terminus)
]

# ── Haversine ─────────────────────────────────────────────────────────────────
EARTH_RADIUS_M = 6_371_000

def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in metres (Sinnott, 1984)."""
    rlat1, rlon1, rlat2, rlon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = rlat2 - rlat1
    dlon = rlon2 - rlon1
    a = math.sin(dlat / 2) ** 2 + math.cos(rlat1) * math.cos(rlat2) * math.sin(dlon / 2) ** 2
    return 2 * EARTH_RADIUS_M * math.asin(math.sqrt(a))


def nearest_cbrt_m(lat: float, lon: float) -> float:
    """Distance in metres to the nearest CBRT station."""
    return min(haversine_m(lat, lon, s[0], s[1]) for s in CBRT_STATIONS)


# ── KD-tree radius query (degree-based approximation) ─────────────────────────
# 1° latitude ≈ 111,320 m  |  1° longitude at 10°N ≈ 109,639 m
# We use a bounding-box pre-filter via KD-tree then exact Haversine for accuracy.

LAT_DEG_PER_M  = 1 / 111_320
LON_DEG_PER_M  = 1 / 109_639   # at ~10°N (Metro Cebu latitude)

def build_kdtree(df_amenity: pd.DataFrame):
    """Return a cKDTree built from (lat, lon) columns of an amenity DataFrame."""
    coords = df_amenity[["lat", "lon"]].values
    return cKDTree(coords)


def count_within_radius(tree: cKDTree, lat: float, lon: float, radius_m: float) -> int:
    """Count POIs within radius_m of (lat, lon) using a degree-space KD-tree."""
    # Convert radius to degrees (slightly over-estimates to avoid misses)
    r_deg = radius_m * max(LAT_DEG_PER_M, LON_DEG_PER_M) * 1.02
    candidate_indices = tree.query_ball_point([lat, lon], r=r_deg)
    if not candidate_indices:
        return 0
    # Exact Haversine filter on candidates
    return sum(
        1 for i in candidate_indices
        if haversine_m(lat, lon, tree.data[i][0], tree.data[i][1]) <= radius_m
    )


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("Enriching ABT with Haversine distances & amenity scores")
    print("=" * 60)

    # ── Load empirical CBD nodes ──────────────────────────────────────────────
    nodes_df = pd.read_csv(CBD_NODES_CSV).set_index("hub_id")
    CBD_NODES = {
        row_id: (row["centroid_lat"], row["centroid_lon"])
        for row_id, row in nodes_df.iterrows()
    }
    print("Loaded CBD nodes:")
    for hub_id, (lat, lon) in CBD_NODES.items():
        poi_count = nodes_df.loc[hub_id, "poi_count"]
        print(f"  {hub_id:25s}: ({lat:.6f}, {lon:.6f})  [{poi_count} POIs]")

    abt = pd.read_csv(ABT_CSV)
    valid = abt["latitude"].notna() & abt["longitude"].notna()
    print(f"\nTotal rows: {len(abt)}  |  with coords: {valid.sum()}")

    # ── 1. Load amenity KD-trees ──────────────────────────────────────────────
    print("\nLoading amenity data…")
    amenity_trees: dict[str, cKDTree] = {}
    for name, path in AMENITY_CSVS.items():
        df = pd.read_csv(path)
        amenity_trees[name] = build_kdtree(df)
        print(f"  {name:12s}: {len(df):>4} POIs")

    # ── 2. Row-by-row enrichment ───────────────────────────────────────────────
    print(f"\nComputing distances and amenity counts (radius = {AMENITY_RADIUS_M} m)…")

    # Build per-hub distance accumulators dynamically
    cbd_dists: dict[str, list] = {hub_id: [] for hub_id in CBD_NODES}
    dist_airport    = []
    dist_cbrt       = []
    scores          = {k: [] for k in AMENITY_CSVS}

    for _, row in abt.iterrows():
        if pd.isna(row["latitude"]) or pd.isna(row["longitude"]):
            for hub_id in CBD_NODES: cbd_dists[hub_id].append(np.nan)
            dist_airport.append(np.nan)
            dist_cbrt.append(np.nan)
            for k in scores: scores[k].append(np.nan)
            continue

        lat, lon = row["latitude"], row["longitude"]

        pass  # CBD distances computed via network after the loop
        dist_airport.append(haversine_m(lat, lon, *AIRPORT))
        dist_cbrt.append(nearest_cbrt_m(lat, lon))

        for name, tree in amenity_trees.items():
            scores[name].append(count_within_radius(tree, lat, lon, AMENITY_RADIUS_M))

    # -- Network distances to CBD nodes
    print("
Computing road network distances to CBD nodes via osmnx...")
    G = load_metro_cebu_graph()
    valid_mask = abt["latitude"].notna() & abt["longitude"].notna()
    valid_coords = list(zip(abt.loc[valid_mask, "latitude"], abt.loc[valid_mask, "longitude"]))
    valid_indices = abt.index[valid_mask].tolist()
    net_dists, net_flags = network_distances_from_sources(G, valid_coords, CBD_NODES)
    fallback_counts = {hub_id: sum(row[hub_id] for row in net_flags) for hub_id in CBD_NODES}
    for hub_id, count in fallback_counts.items():
        if count > 0:
            print(f"  WARNING: {count} Haversine fallbacks for {hub_id}")
    for hub_id in CBD_NODES:
        col_name = f"dist_{hub_id}_m"
        col_vals = [np.nan] * len(abt)
        for list_pos, df_idx in enumerate(valid_indices):
            col_vals[df_idx] = round(net_dists[list_pos][hub_id], 1)
        abt[col_name] = col_vals
    abt["dist_airport_m"]      = [round(v, 1) if not np.isnan(v) else np.nan for v in dist_airport]
    abt["dist_cbrt_nearest_m"] = [round(v, 1) if not np.isnan(v) else np.nan for v in dist_cbrt]
    # -- is_mactan_island flag
    abt["is_mactan_island"] = (abt["city"] == "Lapu-Lapu City").astype(int)
    print(f"
is_mactan_island: {abt['is_mactan_island'].sum()} rows flagged as Lapu-Lapu City")

    for name, vals in scores.items():
        abt[f"amenity_score_{name}"] = vals

    # ── 3. Composite amenity score (weighted sum, 0-normalised per category) ──
    # Normalise each category score by its max so categories are on same scale,
    # then apply weights defined in WEIGHTS.
    print("\nComputing composite amenity score…")
    composite = np.zeros(len(abt))
    for name, w in WEIGHTS.items():
        col = abt[f"amenity_score_{name}"].astype(float)
        col_max = col.max()
        if col_max > 0:
            composite += w * (col / col_max)
    abt["amenity_score_composite"] = composite.round(4)

    # ── 4. Spatial lag ────────────────────────────────────────────────────────
    print(f"Computing spatial lag (mean neighbour price within {SPATIAL_LAG_RADIUS_M} m)…")
    price_arr  = abt["price_php"].values
    coord_arr  = abt[["latitude", "longitude"]].values
    prop_tree  = cKDTree(coord_arr)
    spatial_lag = []

    for i, (lat, lon) in enumerate(coord_arr):
        if np.isnan(lat) or np.isnan(lon):
            spatial_lag.append(np.nan)
            continue
        r_deg = SPATIAL_LAG_RADIUS_M * max(LAT_DEG_PER_M, LON_DEG_PER_M) * 1.02
        neighbours = prop_tree.query_ball_point([lat, lon], r=r_deg)
        neighbour_prices = [
            price_arr[j] for j in neighbours
            if j != i
            and not np.isnan(price_arr[j])
            and haversine_m(lat, lon, coord_arr[j][0], coord_arr[j][1]) <= SPATIAL_LAG_RADIUS_M
        ]
        spatial_lag.append(np.nanmean(neighbour_prices) if neighbour_prices else np.nan)

    abt["spatial_lag_price"] = [round(v) if not np.isnan(v) else np.nan for v in spatial_lag]

    # ── 5. Summary ────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("Enrichment Summary")
    print("=" * 60)
    for hub_id in CBD_NODES:
        col = f"dist_{hub_id}_m"
        print(f"  {hub_id:30s}: mean {abt[col].mean():>7,.0f} m  |  min {abt[col].min():>6,.0f} m  |  max {abt[col].max():>7,.0f} m")
    for col, label in [
        ("dist_airport_m",      "Airport            "),
        ("dist_cbrt_nearest_m", "Nearest CBRT       "),
    ]:
        print(f"  {label}: mean {abt[col].mean():>7,.0f} m  |  min {abt[col].min():>6,.0f} m  |  max {abt[col].max():>7,.0f} m")
    print()
    for name in AMENITY_CSVS:
        col = abt[f"amenity_score_{name}"]
        print(f"amenity_{name:12s} — mean: {col.mean():.1f}  |  max: {col.max()}")
    print(f"amenity_composite     — mean: {abt['amenity_score_composite'].mean():.3f}  |  max: {abt['amenity_score_composite'].max():.3f}")
    print(f"spatial_lag_price     — {abt['spatial_lag_price'].notna().sum()} rows with neighbours  |  mean: ₱{abt['spatial_lag_price'].mean():,.0f}")

    abt.to_csv(ABT_CSV, index=False)
    print(f"\n✅ Saved → {ABT_CSV}")


if __name__ == "__main__":
    main()
