"""
generate_feature_snapshots.py
=============================
Transposed per-stratum feature snapshots (features as rows, example properties as
columns) for the appendix. Uses the EXACT deployed feature matrix per stratum
(finalize_stratified_groupcv.build_features + STRATUM_DROP). Writes a LaTeX
snippet: Manuscript/feature_snapshots.tex (3 tables).
Run: ./.venv/bin/python Scripts/generate_feature_snapshots.py
"""
import os, sys, re
import numpy as np
import pandas as pd

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
import finalize_stratified_groupcv as F

THESIS = os.path.dirname(SCRIPT_DIR)
OUT = os.path.join(THESIS, "Manuscript", "feature_snapshots.tex")
NEXAMPLES = 3

STRATA = [("condo", "abt_condo.csv", "Condominium"),
          ("houses", "abt_houses.csv", "Houses"),
          ("lot", "abt_lot.csv", "Vacant Lot")]

NODE = {"cebu_business_park": "Cebu Business Park", "mandaue_cbd": "Mandaue CBD",
        "mactan_cbd": "Mactan CBD", "srp": "SRP", "talisay_tabunok": "Talisay Tabunok",
        "consolacion": "Consolacion", "naga_city": "Naga City", "airport": "Airport"}


def pretty(col):
    m = re.match(r"dist_(.+)_m$", col)
    if m:
        return f"Dist. to {NODE.get(m.group(1), m.group(1).replace('_', ' ').title())} (m)"
    if col == "mcrai_composite":
        return "MCRAI composite"
    if col.startswith("mcrai_"):
        return "MCRAI: " + col[len("mcrai_"):].replace("_", " ").title()
    if col == "spatial_lag_price":
        return "Neighborhood price / spatial lag (PHP)"
    if col in ("area_sqm", "floor_area_sqm"):
        return "Floor / lot area (sqm)"
    if col == "lot_area_sqm":
        return "Lot area (sqm)"
    if col.startswith("bir_zonal"):
        return "BIR zonal value (PHP)"
    if col.startswith("city_"):
        return "City: " + col[len("city_"):].replace("_", " ")
    if col == "is_mactan_island":
        return "Mactan island flag"
    if col.endswith("_imputed"):
        return col.replace("_", " ").replace("imputed", "imputed flag").capitalize()
    return col.replace("_", " ").capitalize()


def is_binary(col, series):
    return col.startswith(("city_", "is_")) or col.endswith("_imputed") or \
        set(series.dropna().unique()) <= {0, 1, 0.0, 1.0}


def fmt(col, v, binary):
    if pd.isna(v):
        return "--"
    if binary:
        return str(int(round(v)))
    if abs(v) >= 1000 or col.startswith(("dist_", "bir_zonal")) or col in ("spatial_lag_price",):
        return f"{v:,.0f}"
    if col.startswith("mcrai"):
        return f"{v:.2f}"
    if float(v).is_integer():
        return str(int(v))
    return f"{v:.2f}"


def esc(s):
    return s.replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")


def table_for(key, csv, label):
    df = pd.read_csv(os.path.join(F.PROCESSED_DIR, csv)).reset_index(drop=True)
    X, _ = F.build_features(df)
    drop = [c for c in F.STRATUM_DROP.get(key, []) if c in X.columns]
    if drop:
        X = X.drop(columns=drop)
    # choose complete-feature rows that are representative: spread across the
    # price distribution (≈30th/50th/70th percentile) so examples look typical.
    full = X.index[X.notna().all(axis=1)]
    if len(full) < NEXAMPLES:
        full = X.notna().sum(axis=1).sort_values(ascending=False).index
    pps = df.loc[full, "price_per_sqm"]
    idx = []
    for q in [0.3, 0.5, 0.7][:NEXAMPLES]:
        cand = (pps - pps.quantile(q)).abs().sort_values().index
        pick = next((i for i in cand if i not in idx), cand[0])
        idx.append(pick)
    cols = "L{0.46\\textwidth} " + " ".join(["r"] * len(idx))
    head = " & ".join(["\\textbf{Feature}"] + [f"\\textbf{{Property {i+1}}}" for i in range(len(idx))])
    lines = [f"\\begin{{table}}[htbp]",
             f"\\caption{{Feature snapshot --- {label} stratum ({X.shape[1]} model features).}}",
             f"\\label{{tab:snapshot-{key}}}",
             "\\begin{center}", "\\footnotesize",
             f"\\begin{{tabular}}{{{cols}}}", "\\toprule", head + " \\\\", "\\midrule"]
    for col in X.columns:
        binary = is_binary(col, X[col])
        vals = " & ".join(fmt(col, X.loc[r, col], binary) for r in idx)
        lines.append(f"{esc(pretty(col))} & {vals} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{center}", "\\end{table}", ""]
    return "\n".join(lines)


blocks = [table_for(*s) for s in STRATA]
with open(OUT, "w") as fh:
    fh.write("% Auto-generated by Scripts/generate_feature_snapshots.py\n")
    fh.write("\n".join(blocks))
print("wrote", OUT)
for key, _, label in STRATA:
    print(" -", label)
